### PR TITLE
fixes #11773 - allow false values for :include_repos

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note, new test will fail.  have to re-record cassettes

**Comment by ehelms** [comment]
Looks good pending test fixes,  assuming this will be backported to 1.3?

**Comment by jlsherrill** [comment]
Yeah, would be good to try to get it into 2.3.1 or 2.3.2

**Comment by daviddavis** [comment]
APJ

**Pull request merged**
