### PR TITLE
Deprecate oauth

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by sean797** [comment]
I'm not sure if this is really required.. Pulp have deprecated it since 2.4.

**Comment by jlsherrill** [comment]
I don't think we should remove it till pulp drops it completely, but katello could likely stop using it

**Comment by sean797** [comment]
@jlsherrill Katello doesn't use it by default AFAIK, but it currently is configurable by the user.

**Comment by jlsherrill** [comment]
@sean797 right, i think we can remove it it in katello, i just meant we should probably leave it in runcible for the time being in case its in use by anyone else (as there could be other runcible users).  Some time of deprecation would be good.

ACK! Thanks @sean797

**Pull request merged**
