### PR TITLE
Fixes #14888 - Updating cassettes for pulp 2.8.3

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by daviddavis** [comment]
I number of these cassettes were not regenerated. Not sure why.

```
test/fixtures/vcr_cassettes/extensions/repository_misc/generate_applicability_by_ids.yml
test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors/retrieve_distributors.yml
test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_and_publish/publish.yml
test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_and_publish/retrieve_distributors.yml
test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_empty/retrieve_distributors.yml
test/fixtures/vcr_cassettes/resources/repository_misc/generate_applicability.yml
```

**Comment by daviddavis** [comment]
Looks like the repository_misc stuff is no longer in use. I confirmed with @beav around the repo_group cassettes that they aren't being used anymore.

**Comment by daviddavis** [comment]
* test/fixtures/vcr_cassettes/extensions/repository_misc/generate_applicability_by_ids.yml - [no longer exists](https://git.io/vwXyw)
* test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors/retrieve_distributors.yml - [there is no RepoGroupRetrieveDistributors](https://github.com/Katello/runcible/blob/master/test/resources/repository_group_test.rb)
* test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_and_publish/publish.yml - overriden [here](https://git.io/vwX1K)
* test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_and_publish/retrieve_distributors.yml - overriden [here](https://git.io/vwX1K)
* test/fixtures/vcr_cassettes/resources/repo_group_retrieve_distributors_empty/retrieve_distributors.yml
- there is [no retrieve_distributors for RepoGroupRetrieveDistributorsEmpty](https://git.io/vwXyB)
* test/fixtures/vcr_cassettes/resources/repository_misc/generate_applicability.yml - [no longer exists](https://git.io/vwXSW)

**Comment by beav** [comment]
This looks valid to me, the cassettes for repo group stuff got refactored to allow for random IDs, but I never cleaned up the old cassettes that were lying around.

ACK from me

**Pull request merged**
