### PR TITLE
Fixes #13681 - Remove unnecessary param in puppet distributor

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by bbuckingham** [comment]
I am not sure if 'latest' is truly the latest; however, the parameter being deleted is still referenced in the pulp docs.   I am just mentioning in case either the parameter is still supported by pulp or the pulp docs need an update as well.

Ref: http://pulp-puppet.readthedocs.org/en/latest/tech-reference/plugin_conf.html#distributor

**Comment by johnpmitsch** [comment]
@bbuckingham after @jlsherrill talked to the pulp team, he found out that there may be a potential bug iwth sending nil to a puppet distributor absolute path. I've updated to not send absolute path if its nil, which should solve the issues we are seeing in Katello until pulp fixes the bug.

**Comment by bbuckingham** [comment]
@johnpmitsch, Thanks.  That sounds reasonable.  ACK

**Comment by ehelms** [comment]
I aligned this to a 1.6.1 release, if you need this soon please let us know and we'll do a release.

**Comment by ehelms** [comment]
Thanks @johnpmitsch !

**Pull request merged**
