### PR TITLE
Fixes #11925 - Adding SSL attributes for Ostree

### PR DESCRIPTION
**Pull request by parthaa**
To connect with the CDN

### CODE REVIEW

**Comment by jlsherrill** [comment]
APJ

**Comment by ehelms** [comment]
Suppose it might be overloading, but it would be nice to get these attributes for all types.

**Comment by parthaa** [comment]
> Suppose it might be overloading, but it would be nice to get these attributes for all types

pulps attributes are not consistent.  Its ssl_validation for ostree while ssl_verify for rpm and I think docker doesn;t even have these constants so not the greatest idea put it in a super class.

**Comment by ehelms** [comment]
That's a bummer, I was hoping we could two birds one stone and fix this for users http://projects.theforeman.org/issues/11357

**Comment by ehelms** [comment]
Since we track Runcible as its own project in Redmine, could you get and issue for this there and update the PR accordingly?

**Comment by parthaa** [comment]
@ehelms updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
