### PR TITLE
Fixes #13321 - Updated distribution paths in the tests

### PR DESCRIPTION
**Pull request by parthaa**
Relates to this change https://github.com/pulp/pulp_rpm/blob/master/plugins/pulp_rpm/plugins/distributors/yum/configuration.py#L387

https://pulp.plan.io/issues/1520
https://github.com/pulp/pulp_rpm/commit/dbdc20dc4bfc52e4bc7d2b7a3b2bf2323db63d47

### CODE REVIEW

**Comment by beav** [comment]
This change seems reasonable but you may need to re-record some tests to get travis to pass. You may want to just make this change as part of a larger 2.8 PR since I'm guessing you will need to do a big re-record of everything anyway.

**Comment by parthaa** [comment]
@jlsherrill @ehelms - check the commit that adds task group. I needed to add it here because runcible wont run correctly without those changes

@beav added cassettes

**Comment by ehelms** [comment]
So there is the task group addition + cassete updates and then separately the distribution paths change? Or are you saying that you have to change all of this for 2.8 tests to pass?

**Comment by parthaa** [comment]
@ehelms I am saying runcible needs both the task group stuff  + distribution path changes for it to pass with 2.8. I can do the call change

**Comment by beav** [comment]
@ehelms @parthaa would it make sense to re-record all tests for 2.8? IMO it would be good to "level-set" it since we are increasing the Y version of Pulp.

**Comment by parthaa** [comment]
@ehelms @jlsherrill @beav I reverted the task group changes. Going to address those as part of different PR

**Comment by beav** [comment]
:+1:  from me for this PR

**Comment by ehelms** [comment]
Is this the last change required for Runcible to be Pulp 2.8 compliant? I realize its currently tested against a specific beta, but I would be ok releasing a 2.0 of Runcible at this stage.

**Comment by jlsherrill** [comment]
@ehelms actually with the current pulp 2.8 beta i don't know that there were any backwards incompatible changes anymore (as now the group id response requires you to pass in a new parameter).  @parthaa please correct me if i'm wrong

**Comment by parthaa** [comment]
@ehelms @jlsherrill you are correct. No backwards incompatible change. I am moving the task group changes to a different PR.

**Comment by jlsherrill** [comment]
to clarify the change this PR makes is that pulp now requires a '/' on relative paths, whereas before it didn't.  So this is purely changing the tests to run and pass on 2.8

**Comment by ehelms** [comment]
OK - but we should still release a 2.0 for 2.8 due to new features we will be adding that only apply to 2.8, ja?

**Comment by jlsherrill** [comment]
@ehelms with semver that means the minor version should be incremented not the major?

**Comment by ehelms** [comment]
OK - I'll update Redmine to release 1.5 which can include this change and the certificate auth since that is technically a feature as a release?

**Comment by jlsherrill** [comment]
@ehelms yeah that makes sense.  ACK from me!

**Comment by ehelms** [comment]
@parthaa is this ready to go? You had mentioned on IRC regenerating cassettes for a newer Pulp beta.

**Comment by beav** [comment]
@ehelms @parthaa I have a PR to get in for runcible to support repo group stuff but it's post-2.8, not a blocker for 2.8.

Technically it could have gone in 2.6 but I wanted to do it post-2.8 to avoid diff conflicts on VCR test recordings.

**Comment by ehelms** [comment]
ACK - merging and I'll do a release

**Pull request merged**
