### PR TITLE
Fixes #24105 - Add deb_importer options for verifying signatures

### PR DESCRIPTION
**Pull request by m-bucher**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@m-bucher is this done?  it looks like all that is needed

**Comment by m-bucher** [comment]
@jlsherrill I am currently testing a different approach, which does not use the existing `allowed_keys` option, which uses GPG-Key IDs/Fingerprints, but the GPG-Key as text instead.
I will have to add an additional PR to pulp_deb first.
I plan to update all the necessary PRs in pulp_deb, runcible and katello this week.

**Comment by m-bucher** [comment]
Dependency PR has been merged: pulp/pulp_deb#50

**Comment by jlsherrill** [comment]
Thanks @m-bucher !   This doesn't really need to wait for a pulp_deb release.

**Pull request merged**
