### PR TITLE
Fixes #13700 - Updating to support rest-client 1.8.0

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Here's the pr that created the need for this change:  https://github.com/rest-client/rest-client/commit/c215b22bdbcb988dcc40117ff45432b0db25175b

Since pulp doesn't redirect nor is it using cookies there is no need for us to pass in a request.  It would be very difficult to pass in the correct request, we could pass in a dummy request that is incorrect, but nil seemed better since it works.

**Comment by jlsherrill** [comment]
Related to foreman PR: https://github.com/theforeman/foreman/pull/3175

**Comment by ehelms** [comment]
Can you connect this to the Redmine issue?

**Comment by jlsherrill** [comment]
@ehelms connected

**Comment by ehelms** [comment]
Tested against live stable Pulp and everything was good, I also discovered this while testing -- https://github.com/Katello/puppet-pulp/pull/139

**Comment by ehelms** [comment]
Implied, but now not implied ACK

**Comment by ehelms** [comment]
Although, do we want to support 1.7 and 1.8 with an if to make managing the release easier? Or do you want to just try to coordinate everything properly?

**Comment by jlsherrill** [comment]
I contemplated that and mentioned that it would be required in order to do that in the foreman PR.  I'm okay doing that if it makes things easier.  And it will.  Will update

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
Look before you file -- http://projects.theforeman.org/issues/13700  :)

**Comment by jlsherrill** [comment]
updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
