### PR TITLE
Fixes #15915: Bumping test and README to 2.9.1

### PR DESCRIPTION
**Pull request by zjhuntin**
Successfully ran the tests and made the new VCR files.

### CODE REVIEW

**Comment by ehelms** [comment]
@zjhuntin we manage Runcible as a separate subproject inside Redmine and thus don't share issues. Would you mind creating a Runcible specific issue for this change? http://projects.theforeman.org/projects/runcible/issues

**Comment by zjhuntin** [comment]
@ehelms  Will do

**Comment by ehelms** [comment]
Since its a little hard to tell in the diff, did any tests have to change with this?

**Comment by ehelms** [comment]
@zjhuntin can this be closed?

**Pull request closed without merging**
